--- #YAML:1.0
name:               WWW-Translate-Apertium
version:            0.08
abstract:           Open source machine translation
author:
    - Enrique Nell <perl_nell@telefonica.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
    URI::Escape:     1.36
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
